
# Site settings
title: NJCSSA
email: ben-njcssa@gmail.com
description: "Improving the lives of kids in Newark one line of code at a time. Volunteer today to become a programming instructor!"


# Team names, titles and social links
people:
- name: Ben Campbell
  pic: 1
  position: ben.njcssa@gmail.com, NJCSSA Founder
  social:
    - title: github
      url: github.com/benjaminnow

- name: Darrin Sharif
  pic: 2
  position: Newark Kids Code Founder, Council Member of the Central Ward in Newark, Chief Administrative Officer of the Urban League in Newark
  social:
    - title: twitter
      url: twitter.com/dsharif
    - title: linkedin
      url: linkedin.com/in/darrin-sharif-52539b87/
    - title: facebook
      url: facebook.com/darrin.sharif



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/njcssa
  - title: reddit
    url: http://reddit.com/r/njcssa
  - title: discord
    url: https://discordapp.com/channels/491619339087118336/491619339087118340
  - title: instagram
    url: https://www.instagram.com/nj.cs.sa/
  - title: facebook
    url: https://www.facebook.com/njcssa/


# Postal address (add as many lines as necessary)
address:
  - line: 508 Central Avenue
  - line: Newark, NJ

# Build settings
markdown: kramdown
permalink: pretty
