
# Site settings
title: NJCSSA
email: ben@njcssa.org
description: "Improving the lives of kids in Newark one line of code at a time. Volunteer with NJCSSA today to become a programming instructor!"


# Team names, titles and social links
people:
- name: Ben Campbell
  pic: 1
  position: ben@njcssa.org, NJCSSA Founder
  social:
    - title: github
      url: github.com/benjaminnow

- name: Darrin Sharif
  pic: 2
  position: Newark Kids Code Director, Former Council Member of the Central Ward in Newark, Chief Administrative Officer of the Urban League in Newark
  social:
    - title: twitter
      url: twitter.com/dsharif
    - title: linkedin
      url: linkedin.com/in/darrin-sharif-52539b87/
    - title: facebook
      url: facebook.com/darrin.sharif

- name: Risha Surana
  pic: 3
  position: NJCSSA instructor

- name: Robert Zhao
  pic: 4
  position: NJCSSA instructor, Java and Python programmer, Discord:lucasbright8491#8274





# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/njcssa
  - title: reddit
    url: http://reddit.com/r/njcssa
  - title: discord
    url: https://discordapp.com/channels/491619339087118336/491619339087118340
  - title: instagram
    url: https://www.instagram.com/nj.cs.sa/
  - title: facebook
    url: https://www.facebook.com/njcssa/


# History Modal info here:
history:
  - title: Newark Kids Code is founded
    num: 1
    imgs: img/about/founding/founding2.jpg,img/about/founding/founding3.jpg,img/about/founding/founding4.jpg,img/about/founding/founding5.jpg,img/about/founding/founding6.jpg,img/about/founding/founding7.jpg,img/about/founding/founding8.jpg
  - title: Newark Kids Code Graduates 3 classes
    num: 2
    imgs: img/about/graduations/graduation1.jpg,img/about/graduations/graduation2.jpg,img/about/graduations/graduation3.jpg,img/about/graduations/graduation4.jpg,img/about/graduations/graduation5.jpg
  - title: Newark Kids Code buys the Tech House
    num: 3
    imgs: img/about/tech-house/tech-house1.jpg,img/about/tech-house/tech-house2.jpg,img/about/tech-house/tech-house3.jpg,img/about/tech-house/tech-house4.jpg,img/about/tech-house/tech-house5.jpg,
  - title: NJCSSA Founded
    num: 4
    imgs: img/about/njcssa_logo.png


# Postal address (add as many lines as necessary)
address:
  - line: 508 Central Avenue
  - line: Newark, NJ

# Build settings
markdown: kramdown
permalink: pretty


host: 0.0.0.0
